title: Kashi's Website
author: Kashi Deepak
email: kdeepak@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This is my website I made for AP Comp Sci A.
 

# social links
github_username:  kdeepak1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-modernist
